const fs = require('fs');
const path = require('path');

const articles = [
  {
    id: 'a3',
    title: 'Postres con Fresas Fáciles para Verano',
    slug: 'postres-con-fresas-faciles-verano',
    excerpt: 'Recetas refrescantes de fresas perfectas para los días calurosos de verano.',
    metaTitle: 'Postres con Fresas para Verano - 7 Recetas Refrescantes',
    metaDescription: '7 postres refrescantes con fresas perfectos para verano. Fáciles, rápidos y deliciosamente frescos.',
    image: 'https://images.unsplash.com/photo-1563805042-7684c019e1cb?auto=format&fit=crop&q=80&w=800',
    content: `<h2>El verano pide fresas</h2><p>Cuando el calor aprieta, nada mejor que un postre fresco con fresas. Son ligeras, refrescantes y llenas de vitaminas.</p><h2>Fresas congeladas con crema</h2><p>Congela las fresas 2 horas antes y mézclalas con crema fría. Obtendrás una textura tipo helado cremoso sin necesidad de heladera.</p><h2>Smoothie bowl de fresas</h2><p>Licúa fresas congeladas con un poco de leche y sirve en un bowl. Decora con granola, coco y más fresas frescas.</p><h2>Paletas de fresas con crema</h2><p>Mezcla fresas licuadas con crema y vierte en moldes de paleta. Congela 4 horas y tendrás el snack perfecto.</p><h2>Tips para el verano</h2><p>Compra fresas de temporada, son más dulces y baratas. Guárdalas en el refrigerador sin lavar hasta que las vayas a usar.</p>`,
    keywords: ['postres verano fresas', 'recetas refrescantes', 'fresas frescas verano'],
    category: 'Temporada',
    readTime: '5 min',
    datePublished: '2026-04-06',
    pinterestDescription: '☀️ Postres con Fresas para VERANO | 7 recetas refrescantes | Fáciles y deliciosas',
    hashtags: ['#verano', '#postresverano', '#fresasdetemporada'],
    trending: true
  },
  {
    id: 'a4',
    title: 'Recetas Mexicanas de Fresas con Crema Auténticas',
    slug: 'recetas-mexicanas-fresas-con-crema',
    excerpt: 'Las recetas originales de fresas con crema como se preparan en México, desde Oaxaca hasta Sonora.',
    metaTitle: 'Recetas Mexicanas Auténticas de Fresas con Crema',
    metaDescription: 'Recetas auténticas mexicanas de fresas con crema. Desde el estilo feria hasta la versión oaxaqueña. ¡Sabor real!',
    image: 'https://images.unsplash.com/photo-1564049819479-af0600ba3b16?auto=format&fit=crop&q=80&w=800',
    content: `<h2>La tradición mexicana de las fresas con crema</h2><p>En México, las fresas con crema son mucho más que un postre: son una tradición que se encuentra en cada feria, mercado y puesto callejero del país.</p><h2>Estilo Irapuato</h2><p>Irapuato, la "capital mundial de la fresa", tiene su propia versión con crema extra espesa y un toque de rompope.</p><h2>Versión de Feria</h2><p>La versión de feria usa crema ácida Lala, azúcar blanca y las fresas más rojas. Simple pero perfecta.</p><h2>El secreto de la abuela</h2><p>Las abuelas mexicanas siempre agregan un poquito de canela y unas gotas de limón. Ese toque hace toda la diferencia.</p>`,
    keywords: ['recetas mexicanas fresas', 'fresas con crema México', 'postre mexicano tradicional'],
    category: 'Tradición',
    readTime: '5 min',
    datePublished: '2026-04-08',
    pinterestDescription: '🇲🇽 Recetas AUTÉNTICAS Mexicanas de Fresas con Crema | Sabor de feria en casa',
    hashtags: ['#comidamexicana', '#recetasmexicanas', '#tradicionmexicana']
  },
  {
    id: 'a5',
    title: 'Guía Completa: Fresas con Crema para Fiestas',
    slug: 'fresas-con-crema-para-fiestas',
    excerpt: 'Cómo preparar fresas con crema para 50 personas sin estrés. Cantidades, tips y presentación.',
    metaTitle: 'Fresas con Crema para Fiestas - Guía para 50 Personas',
    metaDescription: 'Guía completa para preparar fresas con crema para fiestas. Cantidades exactas para 50 personas y tips de presentación.',
    image: 'https://images.unsplash.com/photo-1587314168485-3236d6710814?auto=format&fit=crop&q=80&w=800',
    content: `<h2>Planificación para fiestas grandes</h2><p>Preparar fresas con crema para muchas personas es fácil si planificas bien. La clave es calcular las cantidades correctas.</p><h2>Cantidades para 50 personas</h2><p>Necesitarás: 10 kg de fresas, 3 litros de crema para batir, 5 latas de leche condensada y 2 litros de crema ácida.</p><h2>Preparación anticipada</h2><p>Puedes preparar la mezcla de cremas un día antes y refrigerarla. Las fresas córtalas máximo 3 horas antes de servir.</p><h2>Estación de fresas DIY</h2><p>Monta una estación donde los invitados armen sus propias copas con diferentes toppings: chocolate, granola, galleta y nueces.</p>`,
    keywords: ['fresas para fiestas', 'postre para muchos', 'fresas con crema cantidades'],
    category: 'Eventos',
    readTime: '7 min',
    datePublished: '2026-04-10',
    pinterestDescription: '🎉 Fresas con Crema para FIESTAS | Guía para 50 personas | Tips de presentación',
    hashtags: ['#fiesta', '#postrefiesta', '#eventfood']
  },
  {
    id: 'a6',
    title: '5 Errores Comunes al Hacer Fresas con Crema',
    slug: '5-errores-comunes-fresas-con-crema',
    excerpt: 'Evita estos errores y logra fresas con crema perfectas cada vez. El #3 te sorprenderá.',
    metaTitle: '5 Errores al Hacer Fresas con Crema - Evítalos',
    metaDescription: 'Los 5 errores más comunes al preparar fresas con crema y cómo evitarlos. Logra el postre perfecto siempre.',
    image: 'https://images.unsplash.com/photo-1495546992359-94a48035efca?auto=format&fit=crop&q=80&w=800',
    content: `<h2>Error #1: Usar fresas sin sabor</h2><p>Las fresas de supermercado a veces están bonitas pero sin sabor. Busca fresas de temporada, pequeñas y muy rojas.</p><h2>Error #2: Batir demasiado la crema</h2><p>Si bates de más, la crema se convierte en mantequilla. Bate solo hasta picos suaves.</p><h2>Error #3: Agregar azúcar a las fresas directamente</h2><p>El azúcar hace que las fresas suelten agua y queden aguadas. Mejor endulza solo la crema.</p><h2>Error #4: No refrigerar</h2><p>Siempre sirve frío. La crema pierde textura a temperatura ambiente.</p><h2>Error #5: Cortar las fresas muy pequeñas</h2><p>Los trozos grandes son más atractivos visualmente y tienen mejor textura en cada bocado.</p>`,
    keywords: ['errores fresas con crema', 'tips cocina postres', 'fresas perfectas'],
    category: 'Tips',
    readTime: '4 min',
    datePublished: '2026-04-12',
    pinterestDescription: '⚠️ 5 ERRORES al hacer Fresas con Crema | El #3 te sorprenderá | Tips pro',
    hashtags: ['#tipscocina', '#errorescocina', '#consejoscocina'],
    trending: true
  },
  {
    id: 'a7',
    title: 'Fresas con Crema: Historia y Origen del Postre',
    slug: 'historia-origen-fresas-con-crema',
    excerpt: 'Descubre la fascinante historia detrás de uno de los postres más amados de Latinoamérica.',
    metaTitle: 'Historia de las Fresas con Crema - Origen del Postre',
    metaDescription: 'La historia completa de las fresas con crema: desde Europa hasta las calles de México. Un postre con siglos de tradición.',
    image: 'https://images.unsplash.com/photo-1541167760496-1628856ab772?auto=format&fit=crop&q=80&w=800',
    content: `<h2>Un postre con siglos de historia</h2><p>La combinación de fresas con crema tiene sus orígenes en la Europa del siglo XVI, cuando Thomas Wolsey servía este postre en los banquetes reales de Inglaterra.</p><h2>La llegada a México</h2><p>Con la conquista española, las fresas llegaron a México y se adaptaron con ingredientes locales como la crema ácida y la canela.</p><h2>Irapuato: La Capital de la Fresa</h2><p>Guanajuato, México, se convirtió en el epicentro de producción de fresas, y con ello, las fresas con crema se volvieron el postre insignia de la región.</p><h2>El postre en la era digital</h2><p>Hoy, las fresas con crema son uno de los postres más fotografiados en redes sociales, con millones de publicaciones en Instagram y Pinterest.</p>`,
    keywords: ['historia fresas con crema', 'origen postre fresas', 'fresas Irapuato'],
    category: 'Cultura',
    readTime: '6 min',
    datePublished: '2026-04-14',
    pinterestDescription: '📚 Historia de las Fresas con Crema | Desde Europa hasta México | Fascinante',
    hashtags: ['#historiacocina', '#culturagastronómica', '#origenes']
  },
  {
    id: 'a8',
    title: 'Cómo Fotografiar Fresas con Crema para Pinterest',
    slug: 'como-fotografiar-fresas-crema-pinterest',
    excerpt: 'Tips profesionales para tomar fotos de comida dignas de Pinterest con tu celular.',
    metaTitle: 'Fotografía de Fresas con Crema para Pinterest - Tips Pro',
    metaDescription: 'Aprende a fotografiar fresas con crema como un profesional. Tips de iluminación, ángulos y edición para Pinterest.',
    image: 'https://images.unsplash.com/photo-1606313564200-e75d5e30476c?auto=format&fit=crop&q=80&w=800',
    content: `<h2>La foto perfecta para Pinterest</h2><p>En Pinterest, la imagen lo es todo. Una buena foto puede significar miles de repins y tráfico a tu blog.</p><h2>Iluminación natural</h2><p>Siempre usa luz natural. Coloca el plato cerca de una ventana. Evita el flash a toda costa.</p><h2>El ángulo cenital (flat lay)</h2><p>El ángulo desde arriba es perfecto para mostrar la presentación completa del postre.</p><h2>Formato vertical 2:3</h2><p>Pinterest favorece las imágenes verticales. Toma tus fotos en formato retrato (2:3) para máximo alcance.</p><h2>Props y styling</h2><p>Usa manteles de lino, cucharas vintage y flores pequeñas como complemento. Menos es más.</p>`,
    keywords: ['fotografía comida Pinterest', 'food photography', 'fotos fresas bonitas'],
    category: 'Pinterest',
    readTime: '5 min',
    datePublished: '2026-04-16',
    pinterestDescription: '📸 Cómo FOTOGRAFIAR Fresas con Crema | Tips pro para Pinterest | Con tu celular',
    hashtags: ['#foodphotography', '#pinteresttips', '#fotosdecomida'],
    featured: true
  },
  {
    id: 'a9',
    title: 'Beneficios de las Fresas: Superalimento Delicioso',
    slug: 'beneficios-fresas-superalimento',
    excerpt: 'Las fresas no solo son deliciosas, son un superalimento lleno de vitaminas y antioxidantes.',
    metaTitle: 'Beneficios de las Fresas - Superalimento y Nutrición',
    metaDescription: 'Descubre los increíbles beneficios nutricionales de las fresas. Antioxidantes, vitamina C y más. ¡Un superalimento!',
    image: 'https://images.unsplash.com/photo-1551024601-bec78aea704b?auto=format&fit=crop&q=80&w=800',
    content: `<h2>Las fresas son un superalimento</h2><p>Con solo 32 calorías por taza, las fresas están cargadas de vitamina C, manganeso y antioxidantes que benefician tu salud.</p><h2>Vitamina C</h2><p>Una taza de fresas contiene el 150% de la vitamina C diaria recomendada. Más que una naranja.</p><h2>Antioxidantes poderosos</h2><p>Los antocianinos en las fresas combaten la inflamación y protegen el corazón.</p><h2>Beneficios para la piel</h2><p>La vitamina C de las fresas estimula la producción de colágeno, mejorando la elasticidad de la piel.</p><h2>Combinación perfecta</h2><p>Al combinar fresas con crema natural, obtienes un postre que es delicioso Y nutritivo. ¡Ganar-ganar!</p>`,
    keywords: ['beneficios fresas', 'fresas superalimento', 'nutrición fresas vitaminas'],
    category: 'Salud',
    readTime: '4 min',
    datePublished: '2026-04-18',
    pinterestDescription: '🍓 BENEFICIOS de las Fresas | Superalimento delicioso | Vitaminas y antioxidantes',
    hashtags: ['#superalimento', '#nutricion', '#saludable']
  },
  {
    id: 'a10',
    title: 'Cómo Empezar un Blog de Recetas Exitoso en Pinterest',
    slug: 'como-empezar-blog-recetas-pinterest',
    excerpt: 'Guía completa para crear un blog de recetas que genere tráfico masivo desde Pinterest.',
    metaTitle: 'Cómo Crear un Blog de Recetas para Pinterest - Guía 2026',
    metaDescription: 'Guía paso a paso para crear un blog de recetas exitoso en Pinterest. SEO, diseño y estrategia de contenido.',
    image: 'https://images.unsplash.com/photo-1590089415225-401ed6f9db8e?auto=format&fit=crop&q=80&w=800',
    content: `<h2>Pinterest es el motor de búsqueda visual #1</h2><p>A diferencia de otras redes sociales, Pinterest funciona como un buscador. Los pins tienen vida útil de meses, no horas.</p><h2>Elige tu nicho específico</h2><p>No hagas "recetas en general". Enfócate en algo específico como "postres con fresas" y domina ese espacio.</p><h2>Optimiza para SEO</h2><p>Usa keywords en tus títulos, descripciones y alt text de imágenes. Pinterest indexa todo este texto.</p><h2>Consistencia es clave</h2><p>Publica al menos 5 pins nuevos por día. Usa herramientas como Tailwind para programar tu contenido.</p><h2>El diseño importa</h2><p>Imágenes verticales 2:3, texto grande y legible, colores llamativos. Así se crean pins que la gente guarda.</p>`,
    keywords: ['blog Pinterest recetas', 'ganar dinero Pinterest', 'SEO Pinterest recetas'],
    category: 'Emprendimiento',
    readTime: '8 min',
    datePublished: '2026-04-20',
    pinterestDescription: '🚀 Cómo EMPEZAR un Blog de Recetas en Pinterest | Guía completa 2026 | Tráfico masivo',
    hashtags: ['#blogrecetas', '#pinterestmarketing', '#emprendimiento'],
    featured: true,
    trending: true
  }
];

const recipes = [
  {
    id: '1',
    title: 'Fresas con Crema Clásica',
    slug: 'fresas-con-crema-clasica',
    description: 'La receta tradicional que todos amamos. Dulce, cremosa y perfecta para cualquier ocasión especial o antojo.',
    metaTitle: 'Fresas con Crema Clásica - Receta Fácil en 15 Minutos',
    metaDescription: 'Aprende a hacer fresas con crema clásica en solo 15 minutos. Receta fácil, cremosa y perfecta para cualquier ocasión.',
    prepTime: '15 min',
    cookTime: '0 min',
    totalTime: '15 min',
    servings: '4-6',
    difficulty: 'Fácil',
    image: 'https://images.unsplash.com/photo-1488477181946-6428a0291777?auto=format&fit=crop&q=80&w=800',
    pinterestDescription: '🍓 Fresas con Crema Clásica | Receta fácil en 15 min | El postre perfecto para cualquier ocasión',
    hashtags: ['#fresasconcrema', '#postrefacil', '#recetasmexicanas', '#postresvirales'],
    ingredients: ['500g de fresas frescas', '1 taza de crema para batir', '1/2 taza de leche condensada', '1 cucharadita de extracto de vainilla', 'Azúcar al gusto'],
    instructions: ['Lava y desinfecta las fresas, retira las hojas y córtalas en mitades.', 'Bate la crema hasta que espese ligeramente.', 'Agrega la leche condensada y la vainilla, mezclando suavemente.', 'Incorpora las fresas a la crema y mezcla bien.', 'Refrigera 15 minutos y sirve frío.'],
    tips: ['Usa fresas bien maduras for mejor sabor.', 'Puedes agregar media crema para textura más fluida.'],
    category: 'Tradicional',
    keywords: ['fresas con crema receta fácil', 'postre con fresas', 'crema batida con fresas'],
    featured: true,
    trending: true,
    datePublished: '2026-04-01'
  },
  {
    id: '2',
    title: 'Fresas con Crema y Leche Condensada',
    slug: 'fresas-con-crema-leche-condensada',
    description: 'Una versión extra dulce y suave con la irresistible leche condensada. El favorito de toda la familia.',
    metaTitle: 'Fresas con Crema y Leche Condensada - Receta Irresistible',
    metaDescription: 'La mejor receta de fresas con crema y leche condensada. Extra dulce, cremosa y lista en 10 minutos.',
    prepTime: '10 min',
    cookTime: '0 min',
    totalTime: '40 min',
    servings: '6',
    difficulty: 'Fácil',
    image: 'https://images.unsplash.com/photo-1541167760496-1628856ab772?auto=format&fit=crop&q=80&w=800',
    pinterestDescription: '🍓 Fresas con Crema y Leche Condensada | Extra dulce y cremosa | Lista en minutos',
    hashtags: ['#lechecondensada', '#fresasconcrema', '#postrefacil', '#recetadulce'],
    ingredients: ['1 kilo de fresas', '1 lata de leche condensada', '1 lata de media crema', '1 taza de crema ácida', 'Vainilla al gusto'],
    instructions: ['Corta las fresas en rebanadas delgadas.', 'Mezcla las tres cremas en un bowl grande.', 'Agrega un chorrito de vainilla.', 'Vierte la mezcla sobre las fresas.', 'Refrigera por 30 minutos antes de servir.'],
    tips: ['Sirve en copas individuales para una presentación Pinterest-worthy.'],
    category: 'Dulce',
    keywords: ['fresas con leche condensada', 'postre tres leches fresas', 'fresas cremosas'],
    featured: true,
    datePublished: '2026-04-03'
  },
  {
    id: '3',
    title: 'Fresas con Crema Estilo Mexicano',
    slug: 'fresas-con-crema-estilo-mexicano',
    description: 'El postre callejero más icónico de México con crema ácida, canela y nuez picada.',
    metaTitle: 'Fresas con Crema Estilo Mexicano - Receta Auténtica',
    metaDescription: 'Receta auténtica de fresas con crema estilo mexicano. Con crema ácida, canela y nuez. ¡Como en las ferias!',
    prepTime: '20 min',
    cookTime: '0 min',
    totalTime: '20 min',
    servings: '4',
    difficulty: 'Fácil',
    image: 'https://images.unsplash.com/photo-1564049819479-af0600ba3b16?auto=format&fit=crop&q=80&w=800',
    pinterestDescription: '🇲🇽 Fresas con Crema Estilo Mexicano | Receta auténtica de feria | Con canela y nuez',
    hashtags: ['#recetamexicana', '#fresasconcrema', '#comidamexicana', '#postremexicano'],
    ingredients: ['Fresas frescas', 'Crema ácida', 'Azúcar', 'Canela en polvo', 'Nuez picada'],
    instructions: ['Limpia las fresas and déjalas enteras o a la mitad.', 'Bate la crema ácida con el azúcar.', 'Mezcla las fresas con la crema generosamente.', 'Espolvorea canela y nuez picada al servir.'],
    tips: ['Usa crema ácida de buena calidad para el sabor auténtico.'],
    category: 'Mexicano',
    keywords: ['fresas con crema mexicana', 'postre mexicano', 'fresas estilo feria'],
    trending: true,
    datePublished: '2026-04-05'
  },
  {
    id: '4',
    title: 'Fresas con Crema Saludable Sin Azúcar',
    slug: 'fresas-con-crema-saludable',
    description: 'Versión fitness con yogurt griego y stevia. Todo el sabor sin las calorías extras.',
    metaTitle: 'Fresas con Crema Saludable Sin Azúcar - Receta Fit',
    metaDescription: 'Receta saludable de fresas con crema sin azúcar. Con yogurt griego y stevia. ¡Perfecta para tu dieta!',
    prepTime: '10 min',
    cookTime: '0 min',
    totalTime: '10 min',
    servings: '2',
    difficulty: 'Fácil',
    image: 'https://images.unsplash.com/photo-1563805042-7684c019e1cb?auto=format&fit=crop&q=80&w=800',
    pinterestDescription: '💪 Fresas con Crema SALUDABLE | Sin azúcar, con yogurt griego | Postre fit perfecto',
    hashtags: ['#recetafit', '#sinazucar', '#postrefit', '#fresassaludable'],
    ingredients: ['2 tazas de fresas', '1 taza de yogurt griego sin azúcar', 'Stevia al gusto', 'Esencia de vainilla', 'Almendras fileteadas'],
    instructions: ['Corta las fresas en cubos.', 'Endulza el yogurt con stevia y vainilla.', 'Mezcla las fresas con el yogurt.', 'Decora con almendras fileteadas.'],
    tips: ['Usa yogurt de coco para versión vegana.'],
    category: 'Saludable',
    keywords: ['fresas con crema sin azúcar', 'postre saludable', 'fresas fit'],
    datePublished: '2026-04-07'
  },
  {
    id: '5',
    title: 'Fresas con Crema y Queso Crema',
    slug: 'fresas-con-crema-queso',
    description: 'Textura aterciopelada tipo cheesecake. El queso crema le da un toque gourmet increíble.',
    metaTitle: 'Fresas con Crema y Queso Crema - Postre Gourmet Fácil',
    metaDescription: 'Fresas con crema y queso crema estilo cheesecake. Textura gourmet en solo 25 minutos.',
    prepTime: '25 min',
    cookTime: '0 min',
    totalTime: '25 min',
    servings: '4-6',
    difficulty: 'Media',
    image: 'https://images.unsplash.com/photo-1464195244916-405fa0a82545?auto=format&fit=crop&q=80&w=800',
    pinterestDescription: '✨ Fresas con Queso Crema | Estilo cheesecake SIN horno | Postre gourmet en 25 min',
    hashtags: ['#cheesecake', '#quesocrema', '#postregourmet', '#fresasconcrema'],
    ingredients: ['500g de fresas', '190g de queso crema', '1/2 taza de crema para batir', '3/4 taza de azúcar glass', 'Ralladura de limón'],
    instructions: ['Bate el queso crema con el azúcar glass.', 'Monta la crema e incorpórala al queso de forma envolvente.', 'Agrega la ralladura de limón.', 'Sirve las fresas con la crema de queso.'],
    tips: ['La ralladura de limón resalta el sabor de la fresa.'],
    category: 'Gourmet',
    keywords: ['fresas con queso crema', 'cheesecake fresas sin horno', 'postre gourmet'],
    featured: true,
    datePublished: '2026-04-09'
  },
  {
    id: '6',
    title: 'Fresas con Crema y Chocolate',
    slug: 'fresas-con-crema-chocolate',
    description: 'La combinación perfecta: fresas frescas, crema batida y chocolate amargo derretido.',
    metaTitle: 'Fresas con Crema y Chocolate - Postre Irresistible',
    metaDescription: 'Fresas con crema y chocolate derretido. La combinación más irresistible para los amantes del chocolate.',
    prepTime: '20 min',
    cookTime: '5 min',
    totalTime: '25 min',
    servings: '4',
    difficulty: 'Fácil',
    image: 'https://images.unsplash.com/photo-1590089415225-401ed6f9db8e?auto=format&fit=crop&q=80&w=800',
    pinterestDescription: '🍫 Fresas con Crema y CHOCOLATE | Postre viral irresistible | Listo en 25 min',
    hashtags: ['#fresasconchocolate', '#postrechocolate', '#postreviral', '#fresasconcrema'],
    ingredients: ['Fresas maduras', 'Crema batida', '100g de chocolate semi-amargo', 'Granola o chispas de chocolate'],
    instructions: ['Coloca las fresas en un tazón.', 'Cubre con crema batida.', 'Derrite el chocolate a baño maría.', 'Vierte el chocolate en hilos sobre la crema.', 'Agrega granola para textura.'],
    tips: ['Usa chocolate con 70% cacao para mejor contraste.'],
    category: 'Chocolate',
    keywords: ['fresas con chocolate', 'postre chocolate fresas', 'fresas crema chocolate'],
    trending: true,
    datePublished: '2026-04-11'
  },
  {
    id: '7',
    title: 'Fresas con Crema en Copa Elegante',
    slug: 'fresas-con-crema-copa-elegante',
    description: 'Presentación sofisticada en capas dentro de copas de cristal. Perfecto para cenas románticas.',
    metaTitle: 'Fresas con Crema en Copa - Postre Elegante para Cenas',
    metaDescription: 'Fresas con crema en copa elegante con capas. Postre perfecto para cenas románticas y ocasiones especiales.',
    prepTime: '30 min',
    cookTime: '0 min',
    totalTime: '30 min',
    servings: '4',
    difficulty: 'Media',
    image: 'https://images.unsplash.com/photo-1587314168485-3236d6710814?auto=format&fit=crop&q=80&w=800',
    pinterestDescription: '🥂 Fresas con Crema en COPA | Postre elegante para cenas especiales | Presentación WOW',
    hashtags: ['#postreelegante', '#cenaromantica', '#fresasencopa', '#postreviral'],
    ingredients: ['Fresas frescas cortadas', 'Crema batida', 'Galletas trituradas', 'Mermelada de fresa', 'Menta fresca'],
    instructions: ['Coloca una capa de galleta triturada en el fondo de cada copa.', 'Agrega una capa de mermelada de fresa.', 'Coloca fresas cortadas.', 'Cubre con crema batida.', 'Repite las capas y decora con menta.'],
    tips: ['Prepara con 2 horas de anticipación para que los sabores se integren.'],
    category: 'Elegante',
    keywords: ['fresas en copa', 'postre elegante fresas', 'parfait de fresas'],
    featured: true,
    datePublished: '2026-04-13'
  },
  {
    id: '8',
    title: 'Fresas con Crema Vegana',
    slug: 'fresas-con-crema-vegana',
    description: 'Versión 100% vegetal con crema de coco batida. Igual de deliciosa, sin lácteos.',
    metaTitle: 'Fresas con Crema Vegana - Receta Sin Lácteos Deliciosa',
    metaDescription: 'Receta vegana de fresas con crema de coco. Sin lácteos, sin azúcar refinada. ¡Deliciosa y saludable!',
    prepTime: '15 min',
    cookTime: '0 min',
    totalTime: '15 min',
    servings: '4',
    difficulty: 'Fácil',
    image: 'https://images.unsplash.com/photo-1495546992359-94a48035efca?auto=format&fit=crop&q=80&w=800',
    pinterestDescription: '🌱 Fresas con Crema VEGANA | Con crema de coco | Sin lácteos y deliciosa',
    hashtags: ['#vegano', '#postrevegano', '#sinlacteos', '#fresasveganas'],
    ingredients: ['Fresas orgánicas', '1 lata de leche de coco refrigerada', 'Sirope de agave', 'Vainilla', 'Coco rallado'],
    instructions: ['Refrigera la lata de coco toda la noche.', 'Separa la parte sólida del líquido.', 'Bate la crema de coco con agave and vainilla.', 'Sirve sobre las fresas frescas.', 'Decora con coco rallado.'],
    tips: ['La lata debe estar mínimo 12 horas en la nevera.'],
    category: 'Vegano',
    keywords: ['fresas con crema vegana', 'postre vegano fresas', 'crema de coco fresas'],
    datePublished: '2026-04-15'
  },
  {
    id: '9',
    title: 'Fresas con Crema y Galleta Oreo',
    slug: 'fresas-con-crema-oreo',
    description: 'La fusión viral del momento: fresas cremosas con trozos de galleta Oreo. Los niños lo aman.',
    metaTitle: 'Fresas con Crema y Oreo - Receta Viral de Pinterest',
    metaDescription: 'Fresas con crema y galleta Oreo triturada. La receta viral de Pinterest que los niños aman. ¡En 10 minutos!',
    prepTime: '10 min',
    cookTime: '0 min',
    totalTime: '10 min',
    servings: '4-6',
    difficulty: 'Fácil',
    image: 'https://images.unsplash.com/photo-1551024601-bec78aea704b?auto=format&fit=crop&q=80&w=800',
    pinterestDescription: '🔥 Fresas con Crema y OREO | Receta viral Pinterest | Los niños lo AMAN',
    hashtags: ['#recetaviral', '#oreo', '#fresasconoreo', '#postreviral'],
    ingredients: ['Fresas frescas', 'Crema batida', '10 galletas Oreo trituradas', 'Leche condensada', 'Chispas de chocolate'],
    instructions: ['Corta las fresas y colócalas en un tazón.', 'Mezcla la crema batida con leche condensada.', 'Vierte sobre las fresas.', 'Espolvorea las Oreos trituradas encima.', 'Agrega chispas de chocolate y sirve.'],
    tips: ['No tritres las Oreos demasiado fino, los trozos dan mejor textura.'],
    category: 'Viral',
    keywords: ['fresas con oreo', 'receta viral fresas', 'postre oreo fresas'],
    trending: true,
    datePublished: '2026-04-17'
  },
  {
    id: '10',
    title: 'Fresas con Crema y Nutella',
    slug: 'fresas-con-crema-nutella',
    description: 'La indulgencia máxima: capas de crema, fresas frescas y generosos remolinos de Nutella.',
    metaTitle: 'Fresas con Crema y Nutella - El Postre Más Indulgente',
    metaDescription: 'Fresas con crema y Nutella: el postre más indulgente y viral. Perfecto para amantes del chocolate con avellana.',
    prepTime: '15 min',
    cookTime: '0 min',
    totalTime: '15 min',
    servings: '4',
    difficulty: 'Fácil',
    image: 'https://images.unsplash.com/photo-1606313564200-e75d5e30476c?auto=format&fit=crop&q=80&w=800',
    pinterestDescription: '😍 Fresas con Crema y NUTELLA | Postre indulgente | El más viral de Pinterest',
    hashtags: ['#nutella', '#fresasconnutella', '#postreviral', '#postreindulgente'],
    ingredients: ['Fresas maduras', 'Crema batida', '1/2 taza de Nutella', 'Avellanas picadas', 'Galletas de vainilla'],
    instructions: ['Corta las fresas en mitades.', 'En copas, alterna capas de fresas y crema.', 'Calienta ligeramente la Nutella y viértela en hilos.', 'Decora con avellanas picadas.', 'Sirve con galletas al lado.'],
    tips: ['Calienta la Nutella 15 segundos en microondas para que fluya mejor.'],
    category: 'Indulgente',
    keywords: ['fresas con nutella', 'postre nutella', 'fresas crema nutella'],
    trending: true,
    featured: true,
    datePublished: '2026-04-19'
  }
];

function migrate() {
  articles.forEach(a => {
    fs.writeFileSync(path.join(__dirname, '../src/content/articles', `${a.slug}.json`), JSON.stringify(a, null, 2));
  });
  recipes.forEach(r => {
    fs.writeFileSync(path.join(__dirname, '../src/content/recipes', `${r.slug}.json`), JSON.stringify(r, null, 2));
  });
  console.log('Migration complete!');
}

migrate();
